### ISSUE TITLE
using with docker-compose

### ISSUE THREAD

**Issue by mehmetkose** [TransactCharlie/nuitka-docker-example#2]
I'm trying to use with docker-compose but Im getting some errors (waitress branch)
![ekran resmi 2017-06-27 13 05 13](https://user-images.githubusercontent.com/706678/27582371-56bb519c-5b39-11e7-863f-385462ec98e6.png)

my docker-compose file like this, any suggestion?

version: "3"
services:
  web:
    build: ./web/
    ports:
      - "8001:8001"

**Comment by TransactCharlie** [comment]
Hi @mehmetkose.

The build process isn't at all simple - the build of the image is currently done by travis-ci. The build instructions are: [https://github.com/TransactCharlie/nuitka-docker-example/blob/waitress/.travis.yml](https://github.com/TransactCharlie/nuitka-docker-example/blob/waitress/.travis.yml)

If you have a look at that you'll see that the Dockerfile is really just a shim -- it's simply the smallest base container with an entrypoint of "app.exe" So while it's possible to *build* the docker image from the Dockerfile, you actually need a compiled app.exe to copy into it.

That's what travis does -- it compiles the app and then builds the dockerfile using the compiled app.exe (and it's DLLs) into the image.

The whole Dockerfile is simply:

```dockerfile
FROM scratch
COPY . /
ENTRYPOINT ["/app.exe"]
```

So - at the moment this project is completely just a POC for the smallest compiled python program I could stuff into a docker image.

A *better* way of doing this, rather than using travis-ci to issue build steps would be to set up the build pipeline *inside docker* -- and then build a docker image inside the docker image.....

which is kinda Inception level crazy. -- doable of course though. hint....

So this project isn't a toolkit for you to build your own compiled apps -- it's more of a POC that I threw together to see what images made with the compiled apps were like. They are smaller than their equivalent alpine linux versions and they are safer as there isn't a shell to get into. Whether that's worth anything is an entirely different matter.

If you wanted to use the waitress app in your docker compose file (without trying to build stuff of your own). You'd need to do this:

```yaml
---

version: "3"

services:
    web:
        image: transactcharlie/nuitka-docker-example:waitress
        ports:
        - "8001:8001"
```
Note that because of the compile options I picked as the build, the docker output is a bit lacking. it doesn't tell you when it's started up..

```
docker-compose -f docker-compose.yml up
Pulling web (transactcharlie/nuitka-docker-example:waitress)...
waitress: Pulling from transactcharlie/nuitka-docker-example
9f2a7c9a51ac: Pull complete
Digest: sha256:00a71d8637dbd6bbd861b0e663f24178b2cf6166e2f3cf101b64481ba449a2ae
Status: Downloaded newer image for transactcharlie/nuitka-docker-example:waitress
Creating downloads_web_1
Attaching to downloads_web_1
web_1  | 2017-06-27T12:52:00 INFO:Hello World!
```

and the curl:
```
curl localhost:8001
```

**Comment by mehmetkose** [comment]
Ok, I'll try move travis code to inside Dockerfile. Actually my web framework is Tornado. So I'll use your way. Thanks.

**Comment by TransactCharlie** [comment]
Hi @mehmetkose -- I spent some time last night refactoring the build.
I set up a new proejct that produces a base nuitka python image to be used to run the compile in.

It should be a lot easier to do now -- and should be reproducable locally -- it's a two step process -- you run "build_and_extract.sh" and then "package_into_base.sh" {name} which will generate an image called {name}
then you can docker run {name}
